version: "3.8"

services:
  flask:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
      - "2222:22"
    volumes:
      - document_root:/var/www/html
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"

  developer:
    build: ./developer_env
    container_name: developer_env
    ports:
      - "5900:5900"  # VNC Server
      - "2223:22"  # SSH
    volumes:
      - document_root:/workspace
    networks:
      - dev
    depends_on:
      - flask
      - postgres

volumes:
  dbdata:
  document_root:

networks:
  dev:
